const translations = {
    en: {
      "header": {
        "title": "Deafness-Aware Lecture Transcription & Note Generator",
        "subtitle": "Your AI-powered assistant for accessible learning."
      },
      "settings": {
        "accessibility": {
          "title": "Accessibility",
          "simplifiedLanguage": "Simplified Language",
          "simplifiedLanguageDesc": "Generate notes using simpler terms.",
          "fontSize": "Adjust Font Size"
        },
        "noteGeneration": {
          "title": "Note Generation",
          "autoGenerate": "Auto-Generate Notes",
          "autoGenerateDesc": "Generate notes automatically after transcription finishes.",
          "outputLanguage": "Output Language",
          "languageOptions": {
            "ENGLISH": "English",
            "ARABIC": "Arabic",
            "BILINGUAL": "Bilingual (English & Arabic)"
          },
          "customGlossary": "Custom Glossary",
          "customGlossaryPlaceholder": "e.g., Photosynthesis, Mitochondria, Quantum Mechanics",
          "customGlossaryDesc": "Comma-separated course-specific terms."
        }
      },
      "transcription": {
        "title": "Transcription",
        "stopButton": "Stop",
        "startLiveButton": "Start Live",
        "uploadButton": "Upload Audio",
        "initializing": "Initializing transcription service...",
        "placeholder": "Your transcription will appear here...",
        "copyButton": "Copy Text",
        "exportPdfButton": "Export as PDF",
        "errorMicrophone": "Failed to start transcription. Please check microphone permissions.",
        "errorApiQuota": "You've exceeded your API usage quota. Please check your plan and billing details. For more information, see <a href=\"https://ai.google.dev/gemini-api/docs/rate-limits\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"font-bold underline\">API Rate Limits</a> or <a href=\"https://ai.dev/usage?tab=rate-limit\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"font-bold underline\">your usage dashboard</a>.",
        "errorGeneric": "An error occurred with the transcription service."
      },
      "notes": {
        "title": "AI Generated Notes",
        "generateButton": "Generate Notes",
        "generatingButton": "Generating...",
        "placeholder": "Generated notes will appear here...",
        "copyButton": "Copy Text",
        "exportPdfButton": "Export as PDF",
        "errorGeneric": "Failed to generate notes."
      },
      "languageSwitcher": {
        "en": "English",
        "ar": "العربية"
      }
    },
    ar: {
      "header": {
        "title": "مولّد النصوص والملاحظات للمحاضرات مع مراعاة الصم",
        "subtitle": "مساعدك المدعوم بالذكاء الاصطناعي للتعلم الميسّر."
      },
      "settings": {
        "accessibility": {
          "title": "إمكانية الوصول",
          "simplifiedLanguage": "لغة مبسطة",
          "simplifiedLanguageDesc": "توليد الملاحظات باستخدام مصطلحات أبسط.",
          "fontSize": "تعديل حجم الخط"
        },
        "noteGeneration": {
          "title": "توليد الملاحظات",
          "autoGenerate": "توليد تلقائي للملاحظات",
          "autoGenerateDesc": "توليد الملاحظات تلقائيًا بعد انتهاء النسخ.",
          "outputLanguage": "لغة الإخراج",
          "languageOptions": {
            "ENGLISH": "الإنجليزية",
            "ARABIC": "العربية",
            "BILINGUAL": "ثنائي اللغة (الإنجليزية والعربية)"
          },
          "customGlossary": "مسرد مخصص",
          "customGlossaryPlaceholder": "مثال: التمثيل الضوئي، الميتوكوندريا، ميكانيكا الكم",
          "customGlossaryDesc": "مصطلحات خاصة بالدورة مفصولة بفواصل."
        }
      },
      "transcription": {
        "title": "النسخ النصي",
        "stopButton": "إيقاف",
        "startLiveButton": "بدء مباشر",
        "uploadButton": "رفع ملف صوتي",
        "initializing": "جاري تهيئة خدمة النسخ...",
        "placeholder": "سيظهر النسخ النصي هنا...",
        "copyButton": "نسخ النص",
        "exportPdfButton": "تصدير كـ PDF",
        "errorMicrophone": "فشل بدء النسخ. يرجى التحقق من أذونات الميكروفون.",
        "errorApiQuota": "لقد تجاوزت حصة استخدام واجهة برمجة التطبيقات الخاصة بك. يرجى مراجعة خطتك وتفاصيل الفوترة. لمزيد من المعلومات، راجع <a href=\"https://ai.google.dev/gemini-api/docs/rate-limits\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"font-bold underline\">حدود معدل واجهة برمجة التطبيقات</a> أو <a href=\"https://ai.dev/usage?tab=rate-limit\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"font-bold underline\">لوحة معلومات الاستخدام الخاصة بك</a>.",
        "errorGeneric": "حدث خطأ في خدمة النسخ."
      },
      "notes": {
        "title": "ملاحظات مولّدة بالذكاء الاصطناعي",
        "generateButton": "توليد الملاحظات",
        "generatingButton": "جاري التوليد...",
        "placeholder": "ستظهر الملاحظات المولّدة هنا...",
        "copyButton": "نسخ النص",
        "exportPdfButton": "تصدير كـ PDF",
        "errorGeneric": "فشل توليد الملاحظات."
      },
      "languageSwitcher": {
        "en": "English",
        "ar": "العربية"
      }
    }
};

type UILanguage = 'en' | 'ar';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const get = (obj: any, path: string) => path.split('.').reduce((o, i) => (o ? o[i] : undefined), obj);


export const t = (key: string, lang: UILanguage): string => {
    const translation = get(translations[lang], key);
    if (!translation) {
        console.warn(`Translation not found for key: ${key} in language: ${lang}`);
        // Fallback to English
        const fallback = get(translations.en, key);
        return fallback || key;
    }
    return translation;
};